language: common-lisp

sudo: false

os:
  - linux
  - osx

env:
  global:
    - ROSWELL_BRANCH=master
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp
    - LISP=abcl
    - LISP=ecl

matrix:
  fast_finish: true
  allow_failures:
    - env: LISP=clisp
    - env: LISP=abcl
    - env: LISP=ecl

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-8-jre

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libev; fi
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ros install sbcl; fi
  - git clone --depth=1 git://github.com/death/monotonic-clock.git ~/common-lisp/monotonic-clock
  - git clone --depth=1 git://github.com/soemraws/parse-float.git ~/common-lisp/parse-float
  - ros install fukamachi/rove

script:
  - rove cl-kraken.asd
